-- Backfills the expanded print_profiles Quality/Strength/Speed/Support/Others
-- fields (mirroring the full Bambu Studio Print Settings tabs) into existing
-- rows. Uses jsonb `||` merge so only missing keys are added and any values a
-- user has already customized are left untouched. Also updates each column's
-- default so newly created rows get the same shape.
--
-- Two extra fixups beyond the usual merge:
--  1. elephant_foot_compensation moved from `others` to `quality` (matching
--     current Bambu Studio) — copied across, then dropped from `others`.
--  2. support.type's old bare "normal"/"tree" values are remapped to the new
--     "normal(auto)"/"tree(auto)" option strings so existing dropdowns still
--     show a selected value instead of going blank.

ALTER TABLE print_profiles
  ALTER COLUMN quality SET DEFAULT '{
    "layer_height": 0.2,
    "first_layer_height": 0.2,
    "mixed_color_sublayer": false,
    "line_width_default": 0.42,
    "line_width_initial_layer": 0.5,
    "outer_wall_line_width": 0.42,
    "line_width_inner_wall": 0.42,
    "line_width_top_surface": 0.42,
    "line_width_sparse_infill": 0.42,
    "line_width_internal_solid_infill": 0.42,
    "line_width_support": 0.42,
    "seam_position": "aligned",
    "seam_away_from_overhangs": false,
    "smart_scarf_seam_application": true,
    "scarf_application_angle_threshold": 155,
    "scarf_around_entire_wall": false,
    "scarf_steps": 10,
    "scarf_joint_for_inner_walls": true,
    "override_filament_scarf_seam_setting": false,
    "role_based_wipe_speed": true,
    "slice_gap_closing_radius": 0.049,
    "resolution": 0.012,
    "arc_fitting": true,
    "xy_hole_compensation": 0,
    "xy_contour_compensation": 0,
    "auto_circle_compensation": false,
    "precision_walls": true,
    "elephant_foot_compensation": 0.0,
    "precise_z_height": false,
    "ironing_type": "no_ironing",
    "wall_generator": "arachne",
    "wall_order": "inner/outer",
    "print_infill_first": false,
    "bridge_flow": 1,
    "thick_bridges": false,
    "only_one_wall_top_surfaces": "Top surfaces",
    "only_one_wall_first_layer": false,
    "smooth_speed_discontinuity_area": true,
    "smooth_coefficient": 80,
    "avoid_crossing_wall": false,
    "smooth_wall_speed_z": false
  }'::jsonb,
  ALTER COLUMN strength SET DEFAULT '{
    "wall_loops": 2,
    "embed_wall_in_infill": false,
    "detect_thin_wall": false,
    "detect_overhang_wall": true,
    "top_surface_pattern": "monotonic",
    "top_surface_density": 100,
    "top_shell_layers": 3,
    "top_shell_thickness": 0.6,
    "top_paint_penetration_layers": 2,
    "bottom_surface_pattern": "monotonic",
    "bottom_surface_density": 100,
    "bottom_shell_layers": 3,
    "bottom_shell_thickness": 0,
    "bottom_paint_penetration_layers": 2,
    "internal_solid_infill_pattern": "Rectilinear",
    "sparse_infill_density": 15,
    "fill_multiline": 1,
    "sparse_infill_pattern": "grid",
    "sparse_infill_anchor_length": "400%",
    "sparse_infill_anchor_max": "20mm",
    "infill_wall_overlap": 15,
    "infill_direction": 45,
    "bridge_direction": 0,
    "min_sparse_infill_threshold": 15,
    "infill_combination": false,
    "detect_narrow_internal_solid_infill": true,
    "ensure_vertical_shell_thickness": "Enabled",
    "detect_floating_vertical_shells": true
  }'::jsonb,
  ALTER COLUMN speed SET DEFAULT '{
    "first_layer": 50,
    "initial_layer_infill": 60,
    "outer_wall": 200,
    "inner_wall": 300,
    "small_perimeters": "50%",
    "small_perimeter_threshold": 0,
    "sparse_infill": 270,
    "solid_infill": 250,
    "vertical_shell_speed": "80%",
    "top_surface": 200,
    "slow_down_for_overhangs": true,
    "overhang_speed_10": 0,
    "overhang_speed_25": 50,
    "overhang_speed_50": 30,
    "overhang_speed_75": 10,
    "overhang_speed_100": 10,
    "slow_down_by_height": false,
    "bridge_speed": 50,
    "gap_infill_speed": 50,
    "support_speed": 150,
    "support_interface_speed": 80,
    "travel": 500,
    "acceleration": 5000,
    "travel_acceleration": 10000,
    "initial_layer_travel_acceleration": 6000,
    "initial_layer_acceleration": 500,
    "outer_wall_acceleration": 5000,
    "inner_wall_acceleration": 0,
    "top_surface_acceleration": 2000,
    "sparse_infill_acceleration": "100%"
  }'::jsonb,
  ALTER COLUMN support SET DEFAULT '{
    "enable": false,
    "type": "tree(auto)",
    "style": "tree_slim",
    "threshold_angle": 30,
    "on_build_plate_only": false,
    "remove_small_overhangs": true,
    "raft_layers": 0,
    "support_filament": "Default",
    "support_interface_filament": "Default",
    "support_initial_layer_density": 90,
    "support_initial_layer_expansion": -1,
    "support_wall_loops": -1,
    "support_top_z_distance": 0.1,
    "support_bottom_z_distance": 0.1,
    "support_base_pattern": "Default",
    "support_base_pattern_spacing": 2.5,
    "support_pattern_angle": 0,
    "support_top_interface_layers": 2,
    "support_bottom_interface_layers": 2,
    "support_interface_pattern": "Default",
    "support_top_interface_spacing": 0.5,
    "support_normal_expansion": 0,
    "support_object_xy_distance": 0.35,
    "support_z_overrides_xy": false,
    "support_object_first_layer_gap": 0.2,
    "support_dont_support_bridges": false,
    "support_independent_layer_height": true
  }'::jsonb,
  ALTER COLUMN others SET DEFAULT '{
    "skirt_loops": 0,
    "skirt_height": 1,
    "brim_type": "auto",
    "brim_width": 5,
    "brim_object_gap": 0.1,
    "prime_tower_enable": true,
    "prime_tower_skip_points": true,
    "prime_tower_internal_ribs": false,
    "prime_tower_width": 35,
    "prime_tower_max_speed": 90,
    "prime_tower_brim_width": 3,
    "prime_tower_infill_gap": 150,
    "prime_tower_rib_wall": true,
    "prime_tower_extra_rib_length": 0,
    "prime_tower_rib_width": 8,
    "prime_tower_fillet_wall": true,
    "purge_into_infill": false,
    "purge_into_support": true,
    "slicing_mode": "Regular",
    "print_sequence": "By layer",
    "spiral_vase": false,
    "timelapse": "Traditional",
    "fuzzy_skin": "None",
    "fuzzy_skin_generator_mode": "Displacement",
    "fuzzy_skin_noise_type": "Classic",
    "fuzzy_skin_point_distance": 0.3,
    "fuzzy_skin_thickness": 0.2,
    "fuzzy_skin_first_layer": false,
    "use_beam_interlocking": false,
    "interlocking_depth": 0,
    "reduce_infill_retraction": "Auto",
    "post_processing_scripts": "",
    "notes": ""
  }'::jsonb;

-- Move elephant_foot_compensation from others -> quality before backfilling
-- the rest, so a user's existing customized value is preserved in its new home.
UPDATE print_profiles
SET quality = quality || jsonb_build_object('elephant_foot_compensation', COALESCE(others->'elephant_foot_compensation', '0.0'::jsonb)),
    others = others - 'elephant_foot_compensation';

-- Remap old bare support type values to the new "(auto)" option strings.
UPDATE print_profiles
SET support = support || jsonb_build_object('type',
  CASE support->>'type'
    WHEN 'tree' THEN 'tree(auto)'
    WHEN 'normal' THEN 'normal(auto)'
    ELSE support->>'type'
  END)
WHERE support->>'type' IN ('tree', 'normal');

UPDATE print_profiles
SET quality = '{
    "mixed_color_sublayer": false,
    "line_width_default": 0.42,
    "line_width_initial_layer": 0.5,
    "line_width_inner_wall": 0.42,
    "line_width_top_surface": 0.42,
    "line_width_sparse_infill": 0.42,
    "line_width_internal_solid_infill": 0.42,
    "line_width_support": 0.42,
    "seam_away_from_overhangs": false,
    "smart_scarf_seam_application": true,
    "scarf_application_angle_threshold": 155,
    "scarf_around_entire_wall": false,
    "scarf_steps": 10,
    "scarf_joint_for_inner_walls": true,
    "override_filament_scarf_seam_setting": false,
    "role_based_wipe_speed": true,
    "slice_gap_closing_radius": 0.049,
    "resolution": 0.012,
    "arc_fitting": true,
    "xy_hole_compensation": 0,
    "xy_contour_compensation": 0,
    "auto_circle_compensation": false,
    "precise_z_height": false,
    "wall_order": "inner/outer",
    "print_infill_first": false,
    "bridge_flow": 1,
    "thick_bridges": false,
    "only_one_wall_top_surfaces": "Top surfaces",
    "only_one_wall_first_layer": false,
    "smooth_speed_discontinuity_area": true,
    "smooth_coefficient": 80,
    "avoid_crossing_wall": false,
    "smooth_wall_speed_z": false
  }'::jsonb || quality,
  strength = '{
    "embed_wall_in_infill": false,
    "detect_thin_wall": false,
    "top_surface_density": 100,
    "top_shell_thickness": 0.6,
    "top_paint_penetration_layers": 2,
    "bottom_surface_density": 100,
    "bottom_shell_thickness": 0,
    "bottom_paint_penetration_layers": 2,
    "internal_solid_infill_pattern": "Rectilinear",
    "fill_multiline": 1,
    "sparse_infill_anchor_length": "400%",
    "sparse_infill_anchor_max": "20mm",
    "infill_wall_overlap": 15,
    "infill_direction": 45,
    "bridge_direction": 0,
    "min_sparse_infill_threshold": 15,
    "infill_combination": false,
    "detect_narrow_internal_solid_infill": true,
    "ensure_vertical_shell_thickness": "Enabled",
    "detect_floating_vertical_shells": true
  }'::jsonb || strength,
  speed = '{
    "initial_layer_infill": 60,
    "small_perimeters": "50%",
    "small_perimeter_threshold": 0,
    "vertical_shell_speed": "80%",
    "slow_down_for_overhangs": true,
    "overhang_speed_10": 0,
    "overhang_speed_25": 50,
    "overhang_speed_50": 30,
    "overhang_speed_75": 10,
    "overhang_speed_100": 10,
    "slow_down_by_height": false,
    "bridge_speed": 50,
    "gap_infill_speed": 50,
    "support_speed": 150,
    "support_interface_speed": 80,
    "travel_acceleration": 10000,
    "initial_layer_travel_acceleration": 6000,
    "initial_layer_acceleration": 500,
    "outer_wall_acceleration": 5000,
    "inner_wall_acceleration": 0,
    "top_surface_acceleration": 2000,
    "sparse_infill_acceleration": "100%"
  }'::jsonb || speed,
  support = '{
    "on_build_plate_only": false,
    "remove_small_overhangs": true,
    "raft_layers": 0,
    "support_filament": "Default",
    "support_interface_filament": "Default",
    "support_initial_layer_density": 90,
    "support_initial_layer_expansion": -1,
    "support_wall_loops": -1,
    "support_top_z_distance": 0.1,
    "support_bottom_z_distance": 0.1,
    "support_base_pattern": "Default",
    "support_base_pattern_spacing": 2.5,
    "support_pattern_angle": 0,
    "support_top_interface_layers": 2,
    "support_bottom_interface_layers": 2,
    "support_interface_pattern": "Default",
    "support_top_interface_spacing": 0.5,
    "support_normal_expansion": 0,
    "support_object_xy_distance": 0.35,
    "support_z_overrides_xy": false,
    "support_object_first_layer_gap": 0.2,
    "support_dont_support_bridges": false,
    "support_independent_layer_height": true
  }'::jsonb || support,
  others = '{
    "skirt_height": 1,
    "brim_object_gap": 0.1,
    "prime_tower_enable": true,
    "prime_tower_skip_points": true,
    "prime_tower_internal_ribs": false,
    "prime_tower_width": 35,
    "prime_tower_max_speed": 90,
    "prime_tower_brim_width": 3,
    "prime_tower_infill_gap": 150,
    "prime_tower_rib_wall": true,
    "prime_tower_extra_rib_length": 0,
    "prime_tower_rib_width": 8,
    "prime_tower_fillet_wall": true,
    "purge_into_infill": false,
    "purge_into_support": true,
    "slicing_mode": "Regular",
    "print_sequence": "By layer",
    "spiral_vase": false,
    "timelapse": "Traditional",
    "fuzzy_skin": "None",
    "fuzzy_skin_generator_mode": "Displacement",
    "fuzzy_skin_noise_type": "Classic",
    "fuzzy_skin_point_distance": 0.3,
    "fuzzy_skin_thickness": 0.2,
    "fuzzy_skin_first_layer": false,
    "use_beam_interlocking": false,
    "interlocking_depth": 0,
    "reduce_infill_retraction": "Auto",
    "post_processing_scripts": "",
    "notes": ""
  }'::jsonb || others;
